### ISSUE TITLE
关于电池电压的疑问

### ISSUE THREAD

**Issue by BruceAKABear** [wangyz1997/ch573-sht3x-beacon#2]
为什么电池电压需要减去2然后乘以100然后在广播呢？

**Comment by wangyz1997** [comment]
为了减小广播包的长度，降低功耗，最好是用1个字节表示电量。纽扣电池满电状态一般是3.2V左右，放电到没电一般是2.5V左右，用0-255表示2.00V-4.55V正好可以完美覆盖这个范围，假如用锂电池也可以完美覆盖工作电压区间。
